"""
This is a class that classifies a photo as a dog or a cat given a neural network.

@author Ben Scarbrough
@version 12/3/19
"""

import os
import sys
import cv2
import tensorflow as tf
import numpy as np

categories = ["Cat", "Dog"]
image_size = 100 # Pixels


def main():
    """
    This is the main function. To run by giving it the path to an image directory and the name of the neural network that will be generated.
    The image directory must be entered inside quotes.
    """
    # If the program is given more than one argument (2 because python takes the program as the first argument) exit.
    if len(sys.argv) < 3:
        print("This program takes two arguments, an image directory, and the name for the neural network file generated by this program.")
        sys.exit(0)
    else:
        global nn, images # Make global variables for path and neural network name
        images = []
        nn = sys.argv[1]
        if not os.path.exists(nn):
            print(str("The neural network " + nn + " does not exist."))
            sys.exit(0)

        for i in range(len(sys.argv)-2):
            if not os.path.exists(sys.argv[i+2]):
                print(str("The image " + sys.argv[i+2] + " does not exist."))
                sys.exit(0)
            images.append(sys.argv[i+2])

        _prep_img()



def _prep_img():
    """
    A function to prep the images to be predicted.
    """
    img_arr = []
    for i in images:
        array = cv2.imread(i, cv2.IMREAD_GRAYSCALE) # convert the images to an array
        temp = cv2.resize(array, (image_size, image_size)) # Resize the array to the size of the images
        img_arr.append(temp.reshape(-1, image_size, image_size, 1))

    _predict_img(img_arr)


def _predict_img(array):
    """
    A function to predict the image.
    """
    model = tf.keras.models.load_model(nn)

    for i in range(len(array)):
        try:
            guess = model.predict(array[i]) # Predict the image
            cat = categories[int(round(guess[0][0]))] #get which category the image is (0 for cat, 1 for dog)
            print(str(images[i] + " , " + cat)) # Print out the image name + what it is.
        except Exception as e:
            print(e)



# Put at the bottom, runs the program from main.
if __name__ == "__main__":
    main()
